// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sge_api.Data;

#nullable disable

namespace sge_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250304175716_FixColumnNames")]
    partial class FixColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sge_api.Models.Codigos_Verificacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("expiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fecha_generacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("usado")
                        .HasColumnType("boolean");

                    b.Property<int>("usuario_id")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("CodigosVerificacion");
                });

            modelBuilder.Entity("sge_api.Models.Empleado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("apellido_materno")
                        .HasColumnType("text");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .HasColumnType("text");

                    b.Property<string>("email_corporativo")
                        .HasColumnType("text");

                    b.Property<string>("email_personal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("empresa_Id")
                        .HasColumnType("integer");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("numero_identificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("primer_nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("segundo_nombre")
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .HasColumnType("text");

                    b.Property<string>("tipo_documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("empresa_Id");

                    b.HasIndex("numero_identificacion")
                        .IsUnique();

                    b.ToTable("empleado");
                });

            modelBuilder.Entity("sge_api.Models.Empresa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ciudad")
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha_fundacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("logo_url")
                        .HasColumnType("text");

                    b.Property<string>("nombre_comercial")
                        .HasColumnType("text");

                    b.Property<string>("pais")
                        .HasColumnType("text");

                    b.Property<string>("razon_social")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sector")
                        .HasColumnType("text");

                    b.Property<string>("sitio_web")
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .HasColumnType("text");

                    b.Property<string>("tipo_empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("sge_api.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("bloqueado")
                        .HasColumnType("boolean");

                    b.Property<int>("empleado_id")
                        .HasColumnType("integer");

                    b.Property<int>("empleadoid")
                        .HasColumnType("integer");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_ultimo_login")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("intentos_fallidos")
                        .HasColumnType("integer");

                    b.Property<string>("numero_identificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("empleadoid");

                    b.HasIndex("usuario")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("sge_api.Models.Codigos_Verificacion", b =>
                {
                    b.HasOne("sge_api.Models.Users", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("sge_api.Models.Empleado", b =>
                {
                    b.HasOne("sge_api.Models.Empresa", "empresa")
                        .WithMany()
                        .HasForeignKey("empresa_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empresa");
                });

            modelBuilder.Entity("sge_api.Models.Users", b =>
                {
                    b.HasOne("sge_api.Models.Empleado", "empleado")
                        .WithMany()
                        .HasForeignKey("empleadoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
